name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker
      uses: actions/setup-docker@v1

    - name: Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PASSWORD }}

    - name: Build arm64 image
      run: |
        docker build -t ghcr.io/${{ env.REPOSITORY }}:arm64-${{ env.TAG }} .
        docker push ghcr.io/${{ env.REPOSITORY }}:arm64-${{ env.TAG }}

    - name: Build amd64 image
      run: |
        docker build -t ghcr.io/${{ env.REPOSITORY }}:amd64-${{ env.TAG }} .
        docker push ghcr.io/${{ env.REPOSITORY }}:amd64-${{ env.TAG }}
