name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Buildx
      run: |
        echo "Setting up Buildx"
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker run --rm docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
        docker buildx create --use --name mybuilder
        docker buildx inspect --bootstrap

    - name: Build and push Docker image for arm64 architecture
      run: |
        echo "Building and pushing Docker image for arm64 architecture"
        docker buildx build --platform linux/arm64 --push -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:arm64 .

    - name: Build and push Docker image for amd64 architecture
      run: |
        echo "Building and pushing Docker image for amd64 architecture"
        docker buildx build --platform linux/amd64 --push -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:amd64 .
