name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image for arm64 architecture
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/SuperBeppe98/zhonya-s-stats:arm64-latest
        context: .

    - name: Build Docker Image for amd64 architecture
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/superbeppe98/zhonya-s-stats:amd64-latest
        context: .
      
    - name: Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PASSWORD }}
